### ISSUE TITLE
Passing Value and Retrieve 

### ISSUE THREAD

**Issue by celilshn** [invissvenska/ModalBottomSheetDialog#14]
How to pass an (myObject) id to fragment and how to retrieve back into OnItemSelected interface ? 
Big Regards for this library ..

**Comment by invissvenska** [comment]
Do you mean you do not have an item resource file but an Object which you want to add in the bottomsheet and you want to know which of the objects has been clicked on? Or do you have another structure, if so can you explain some more on it?

**Comment by celilshn** [comment]
> Do you mean you do not have an item resource file but an Object which you want to add in the bottomsheet and you want to know which of the objects has been clicked on? Or do you have another structure, if so can you explain some more on it?

Not really. I solved that with defining global variable at my activity .
