### ISSUE TITLE
Not working direct in fragments

### ISSUE THREAD

**Issue by webserveis** [invissvenska/ModalBottomSheetDialog#8]
Errror
>     java.lang.IllegalStateException: Activity or Fragment need to implements ModalBottomSheetDialog.Listener

### My implementation
```kotlin
class FirstFragment : Fragment(R.layout.fragment_first), ModalBottomSheetDialog.Listener {
....
override fun onItemSelected(tag: String?, item: Item?) {
    }
```

call ModalBottomSheetDialog
```kotlin
val dialog = ModalBottomSheetDialog.Builder()
        .setHeader("options")

        .add(R.menu.menu_msg)
        .setRoundedModal(true)
        .build()
dialog.show(requireActivity().supportFragmentManager, "bottomSheetOptions")

```

**Comment by invissvenska** [comment]
Try to use:
`dialog.show(parentFragmentManager, "bottomSheetOptions")`
instead of:
`dialog.show(requireActivity().supportFragmentManager, "bottomSheetOptions")`

**Comment by invissvenska** [comment]
Closed issue due inactivity
